/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
#include  "OutputScheme.h"

CcOutputScheme_t *
CcOutputScheme(const CcOutputSchemeType_t * type, CcGlobals_t * globals,
	       CcArguments_t * arguments)
{
    CcOutputScheme_t * self = (CcOutputScheme_t *)CcObject(&type->base);
    self->globals = globals;
    self->arguments = arguments;
    return (CcOutputScheme_t *)self;
}

void
CcOutputScheme_Destruct(CcOutputScheme_t * self)
{
    CcObject_Destruct(&self->base);
}

const CcOutputFile_t *
CcOutputScheme_List(const CcOutputScheme_t * self)
{
    const CcOutputSchemeType_t * type =
	(const CcOutputSchemeType_t *)self->base.type;
    return type->list(self);
}

CcsBool_t
CcOutputScheme_Write(CcOutputScheme_t * self, FILE * outfp,
		     const char * func, const char * param)
{
    const CcOutputSchemeType_t * type =
	(const CcOutputSchemeType_t *)self->base.type;
    return type->write(self, outfp, func, param);
}
