# -*- python -*-
# Author: Charles Wang <charlesw123456@gmail.com>
# License: GPLv2

Import('env', 'lib', 'cocosrc_lib')

env.Program('AutoTests', ['AutoTests.c', 'TestBitArray.c', 'TestCharSet.c',
                          cocosrc_lib, lib])
env.Program('TestScanner', ['TestScanner.c', cocosrc_lib, lib])
env.Program('TestXmlScanner', ['TestXmlScanner.c', cocosrc_lib, lib],
            LIBS=['expat'])
