# -*- python -*-
# Author: Charles Wang <charlesw123456@gmail.com>
# License: GPLv2

import os.path

SConscript(os.path.join('basic', 'SConscript'))
SConscript(os.path.join('csharp', 'SConscript'))
SConscript(os.path.join('rss', 'SConscript'))
