/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
#include  <ctype.h>
#include  <dirent.h>
#include  <errno.h>
#include  <limits.h>
#include  <stdio.h>
#include  <stdlib.h>
#include  <string.h>
#include  "config.h"

static char prefixbuf[256];

static const char *
CocoGetPrefix(const char * tempdir)
{
    FILE * fp; size_t rc; char * ptr;
    char tempprefix[PATH_MAX];
    snprintf(tempprefix, sizeof(tempprefix), "%s/PREFIX", tempdir);
    if (!(fp = fopen(tempprefix, "r"))) return NULL;
    rc = fread(prefixbuf, 1, sizeof(prefixbuf) - 1, fp);
    fclose(fp);
    if (rc < 0) return NULL;
    prefixbuf[rc] = 0;
    ptr = strchr(prefixbuf, '\n');
    if (ptr) *ptr = 0;
    return prefixbuf;
}

static int
CocoCopy(const char * srcfn, const char * tgtfn)
{
    FILE * srcfp, * tgtfp;
    size_t rc; char buf[4096];
    if (!(srcfp = fopen(srcfn, "r"))) {
	fprintf(stderr, "Can not open %s for read.\n", srcfn);
	goto errquit0;
    }
    if (!(tgtfp = fopen(tgtfn, "w"))) {
	fprintf(stderr, "Can not open %s for write.\n", tgtfn);
	goto errquit1;
    }
    while ((rc = fread(buf, 1, sizeof(buf), srcfp)) > 0)
	if (fwrite(buf, 1, rc, tgtfp) < rc) {
	    fprintf(stderr, "Copy %s to %s failed.\n", srcfn, tgtfn);
	    goto errquit2;
	}
    fclose(tgtfp);
    fclose(srcfp);
    return 0;
 errquit2:
    fclose(tgtfp);
 errquit1:
    fclose(srcfp);
 errquit0:
    return -1;
}

static const char * const suffixes[] = {
    "Parser", "Scanner", NULL
};

static int
CocoConvert(const char * srcprefix, const char * tgtprefix,
	    const char * srcfn, const char * tgtfn)
{
    char lnbuf[4096];
    FILE * srcfp, * tgtfp;
    char * start0, * start1, * cur;
    const char * const * suffix;
    int srcprefixlen = strlen(srcprefix);

    if (!(srcfp = fopen(srcfn, "r"))) {
	fprintf(stderr, "Can not open %s for read.\n", srcfn);
	goto errquit0;
    }
    if (!(tgtfp = fopen(tgtfn, "w"))) {
	fprintf(stderr, "Can not open %s for write.\n", tgtfn);
	goto errquit1;
    }

    while (fgets(lnbuf, sizeof(lnbuf), srcfp)) {
	start0 = start1 = lnbuf;
	for (;;) {
	    cur = strstr(start1, srcprefix);
	    if (cur == NULL) break;
	    for (suffix = suffixes; *suffix; ++suffix)
		if (!strncmp(cur + srcprefixlen, *suffix, strlen(*suffix))) {
		    *cur = 0; fputs(start0, tgtfp);
		    fputs(tgtprefix, tgtfp);
		    fputs(*suffix, tgtfp);
		    start0 = start1 = cur + srcprefixlen + strlen(*suffix);
		    break;
		}
	    if (!*suffix) start1 = cur + srcprefixlen;
	}
	fputs(start0, tgtfp);
    }

    fclose(tgtfp);
    fclose(srcfp);
    return 0;
 errquit1:
    fclose(srcfp);
 errquit0:
    return -1;
}

int
main(int argc, char * argv[])
{
    int rc;
    const char * scheme, * srcprefix, * tgtprefix, * cur;
    char tempdpath[PATH_MAX], * tempfnstart;
    DIR * tempd; struct dirent * result;
#ifdef HAVE_READDIR_R
    struct dirent entry;
#endif

    if (argc == 2) {
	scheme = argv[1]; tgtprefix = NULL;
    } else if (argc == 3) {
	scheme = argv[1]; tgtprefix = argv[2];
    } else {
	fprintf(stderr, "%s SCHEMES-NAME [TARGET-PREFIX]\n", argv[0]);
	return -1;
    }

    for (cur = scheme; *cur; ++cur)
	if (!isalnum(*cur)) {
	    fprintf(stderr, "Invalid SCHEMES-NAME: %s\n", scheme);
	    return -1;
	}
    if (tgtprefix) {
	for (cur = tgtprefix; *cur; ++cur)
	    if (!isalnum(*cur)) {
		fprintf(stderr, "Invalid TARGET-PREFIX: %s\n", tgtprefix);
		return -1;
	    }
    }

    tempfnstart = tempdpath +
	snprintf(tempdpath, sizeof(tempdpath), "%s/%s/%s",
		 DATADIR, PACKAGE, scheme);
    tempd = opendir(tempdpath);
    if (tempd == NULL) {
	fprintf(stderr, "Open directory %s failed: %d(%s).\n",
		tempdpath, errno, strerror(errno));
	return -1;
    }

    srcprefix = CocoGetPrefix(tempdpath);

    rc = 0;
    for (;;) {
#ifdef HAVE_READDIR_R
	if (readdir_r(tempd, &entry, &result) < 0) {
	    fprintf(stderr, "Read directory %s failed: %d(%s).\n",
		    tempdpath, errno, strerror(errno));
	    return -1;
	}
#else
	result = readdir(tempd);
#endif
	if (result == NULL) break;
	if (!strcmp(result->d_name, ".")) continue;
	if (!strcmp(result->d_name, "..")) continue;
	if (!strcmp(result->d_name, "PREFIX")) continue;
	snprintf(tempfnstart, sizeof(tempdpath) - (tempfnstart - tempdpath),
		 "/%s", result->d_name);
	if (srcprefix != NULL) {
	    if (CocoConvert(srcprefix, tgtprefix,
			    tempdpath, result->d_name) < 0)
		rc = -1;
	    else
		printf("%s to %s converted.\n", tempdpath, result->d_name);
	} else {
	    if (CocoCopy(tempdpath, result->d_name) < 0)
		rc = -1;
	    else
		printf("%s to %s copied.\n", tempdpath, result->d_name);
	}
	*tempfnstart = 0;
    }
    closedir(tempd);
    return rc;
}
