/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
#include  "CGlobals.h"
#include  "Token.h"

CcsGlobals_t *
CcsGlobals(CcsGlobals_t * self, const char * fname, FILE * errfp)
{
    if (!CcsErrorPool(&self->error, errfp)) goto errquit0;
    self->xmlscanner = NULL; self->xmlparser = NULL;
    if (!(self->scanner = CcsScanner(&self->u.c.ScannerSpace, self, fname)))
	goto errquit1;
    if (!(self->parser = CcsParser(&self->u.c.ParserSpace, self)))
	goto errquit2;
    return self;
 errquit2:
    CcsScanner_Destruct(self->scanner);
 errquit1:
    CcsErrorPool_Destruct(&self->error);
 errquit0:
    return NULL;
}

CcsGlobals_t *
CcsGlobalsXml(CcsGlobals_t * self, const char * fname, FILE * errfp)
{
    if (!CcsErrorPool(&self->error, errfp)) goto errquit0;
    self->scanner = NULL; self->parser = NULL;
    if (!(self->xmlscanner =
	  CcsXmlScanner(&self->u.xml.XmlScannerSpace, self, fname)))
	goto errquit1;
    if (!(self->xmlparser = CcsXmlParser(&self->u.xml.XmlParserSpace, self)))
	goto errquit2;
    return self;
 errquit2:
    CcsXmlScanner_Destruct(self->xmlscanner);
 errquit1:
    CcsErrorPool_Destruct(&self->error);
 errquit0:
    return NULL;
}

void
CcsGlobals_Destruct(CcsGlobals_t * self)
{
    if (self->parser) CcsParser_Destruct(self->parser);
    if (self->scanner) CcsScanner_Destruct(self->scanner);
    if (self->xmlparser) CcsXmlParser_Destruct(self->xmlparser);
    if (self->xmlscanner) CcsXmlScanner_Destruct(self->xmlscanner);
    CcsErrorPool_Destruct(&self->error);
}

void
CcsGlobals_Parse(CcsGlobals_t * self)
{
    if (self->parser) CcsParser_Parse(self->parser);
    if (self->xmlparser) CcsXmlParser_Parse(self->xmlparser);
}

void
CcsGlobals_Warning(CcsGlobals_t * self, const CcsToken_t * t,
		   const char * format, ...)
{
    va_list ap;
    va_start(ap, format);
    if (t) CcsErrorPool_VWarning(&self->error, t->line, t->col, format, ap);
    else CcsErrorPool_VWarning(&self->error, 0, 0, format, ap);
    va_end(ap);
}

void
CcsGlobals_SemErr(CcsGlobals_t * self, const CcsToken_t * t,
		  const char * format, ...)
{
    va_list ap;
    va_start(ap, format);
    if (t) CcsErrorPool_VError(&self->error, t->line, t->col, format, ap);
    else CcsErrorPool_VError(&self->error, 0, 0, format, ap);
    va_end(ap);
}

void
CcsGlobals_SemErrLC(CcsGlobals_t * self, int line, int col,
		    const char * format, ...)
{
    va_list ap;
    va_start(ap, format);
    CcsErrorPool_VError(&self->error, line, col, format, ap);
    va_end(ap);
}

void CcsGlobals_Fatal(CcsGlobals_t * self, const CcsToken_t * t,
		      const char * format, ...)
{
    va_list ap;
    va_start(ap, format);
    if (t) CcsErrorPool_VFatal(&self->error, t->line, t->col, format, ap);
    else CcsErrorPool_VFatal(&self->error, 0, 0, format, ap);
    va_end(ap);
}
