/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
#include  "c/COutputScheme.h"

static const CcOutputInfo_t CcCOutputScheme_OutputInfos[] = {
    { "Scanner.c" },
    { "Parser.c" },
    { "Parser.h" },
    { NULL }
};

static CcsBool_t
COS_Declarations(CcOutputScheme_t * self, FILE * outfp)
{
}

static CcsBool_t
COS_Chars2States(CcOutputScheme_t * self, FILE * outfp)
{
}

static CcsBool_t
COS_Identifiers2KeywordKinds(CcOutputScheme_t * self, FILE * outfp)
{
}

static CcsBool_t
COS_Comments(CcOutputScheme_t * self, FILE * outfp)
{
}

static CcsBool_t
COS_Scan1(CcOutputScheme_t * self, FILE * outfp)
{
}

static CcsBool_t
COS_Scan2(CcOutputScheme_t * self, FILE * outfp)
{
}

static CcsBool_t
COS_Scan3(CcOutputScheme_t * self, FILE * outfp)
{
}

static CcsBool_t
CcCOutputScheme_write(CcOutputScheme_t * self, FILE * outfp,
		      const char * func, const char * param)
{
    if (!strcmp(func, "declarations")) {
	return COS_Declarations(self, outfp);
    } else if (!strcmp(func, "chars2states")) {
	return COS_Chars2States(self, outfp);
    } else if (!strcmp(func, "identifiers2keywordkinds")) {
	return COS_Identifiers2KeywordKinds(self, outfp);
    } else if (!strcmp(func, "comments")) {
	return COS_Comments(self, outfp);
    } else if (!strcmp(func, "scan1")) {
	return COS_Scan1(self, outfp);
    } else if (!strcmp(func, "scan2")) {
	return COS_Scan2(self, outfp);
    } else if (!strcmp(func, "scan3")) {
	return COS_Scan3(self, outfp);
    }
    fprintf(stderr, "Unknown section '%s' encountered.\n", func);
    return FALSE;
}

static void
CcCOutputScheme_Destruct(CcObject_t * self)
{
    CcCOutputScheme_t * ccself = (CcCOutputScheme_t *)self;
    CcOutputScheme_Destruct(self);
}

static const CcOutputSchemeType_t COutputSchemeType = {
    { sizeof(CcCOutputScheme_t), "COutputScheme", CcCOutputScheme_Destruct },
    CcCOutputScheme_OutputInfos, CcCOutputScheme_write
};

CcCOutputScheme_t *
CcCOutputScheme(CcGlobals_t * globals, CcArguments_t * arguments)
{
    CcCOutputScheme_t * self = (CcCOutputScheme_t *)
	CcOutputScheme(&COutputSchemeType, globals, arguments);
    return self;
}
