/*---- license ----*/
/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
/*---- enable ----*/
#ifndef  COCO_PARSER_H
#define  COCO_PARSER_H

#ifndef  COCO_CDEFS_H
#include  "CDefs.h"
#endif

EXTC_BEGIN

/*---- headerdef ----*/
/*---- enable ----*/

struct CcsParser_s {
    CcsGlobals_t  * globals;
    /*
    int             errDist;
    int             minErrDist;

    Scanner_t     * scanner;
    Errors_t        errors;
    */
    CcsToken_t    * t;
    CcsToken_t    * la;
    /*
    int             maxT;
    */
    /*FILE          * trace;*/
    /*Tab_t         * tab;*/
    /*CcsParserGen_t   * pgen;*/
    /*char          * tokenString;*/
    /*char          * noString;*/
    /*Bool_t          genScanner;*/
    /*DFA_t         * dfa;*/
    /*---- declarations ----*/
    /*---- enable ----*/
};

CcsParser_t * CcsParser(CcsParser_t * self, CcsGlobals_t * globals);
void CcsParser_Destruct(CcsParser_t * self);
void CcsParser_SynErr(CcsParser_t * self, int n);
void CcsParser_SemErr(CcsParser_t * self, const char * format, ...);
void CcsParser_Parse(CcsParser_t * self);

EXTC_END

#endif  /* COCO_PARSER_H */
