# -*- python -*-
# Author: Charles Wang <charlesw123456@gmail.com>
# License: GPLv2

import os.path

env = Environment(CCFLAGS = ['-g', '-Wall'],
                  CPPPATH = [os.getcwd()])
env.ParseConfig('pkg-config --cflags --libs glib-2.0')
lib = env.Library('coco', ['Defs.c', 'BitArray.c', 'CharSet.c',
                           'Position.c', 'Symbol.c'])

Export('env', 'lib')
SConscript(os.path.join('tests', 'SConscript'))

env.Program('Coco', ['Coco.c', 'DFA.c', 'Tab.c', lib])
env.Program('CocoXml', ['CocoXml.c', lib])
