# -*- python -*-
# Author: Charles Wang <charlesw123456@gmail.com>
# License: GPLv2

import os.path

env = Environment(CCFLAGS = ['-g', '-Wall'])
env.ParseConfig('pkg-config --cflags --libs glib-2.0')

lib = env.Library('coco', ['BitArray.c'])
env.Program('Coco', ['Coco.c', 'DFA.c', lib])
env.Program('CocoXml', ['CocoXml.c', lib])
