# -*- python -*-
# Author: Charles Wang <charlesw123456@gmail.com>
# License: GPLv2

Import('env', 'lib')

env.Program('TestRss', ['TestRss.c', 'RssData.c', 'Scanner4Xml.c',
                        'Parser4Xml.c', 'Data4Xml.c', lib])
