# -*- python -*-
# Author: Charles Wang <charlesw123456@gmail.com>
# License: GPLv2

Import('env', 'lib', 'cocosrc_lib')

if 'expat' in env['COCO_FEATURES']:
    env.Program('TestRss', ['TestRss.c', 'RssData.c', 'Scanner4Xml.c',
                            'Parser4Xml.c', cocosrc_lib, lib],
                LIBS = ['expat'])
