/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
#include  "c/COutputScheme.h"
#include  "lexical/Action.h"
#include  "lexical/CharSet.h"
#include  "lexical/Comment.h"
#include  "lexical/State.h"
#include  "lexical/Target.h"
#include  "lexical/Transition.h"
#include  "syntax/Nodes.h"

/* When the number of possible terminals is greater than maxTerm,
   symSet is used. */
#define  maxTerm  3

static const CcOutputInfo_t CcCOutputScheme_OutputInfos[] = {
    { "Scanner.c" },
    { "Parser.c" },
    { "Parser.h" },
    { NULL }
};

static const char *
CharRepr(char * buf, size_t szbuf, int ch)
{
    if (ch == '\\') {
	snprintf(buf, szbuf, "'\\\\'");
    } else if (ch == '\'') {
	snprintf(buf, szbuf, "'\\\''");
    } else if (ch >= 32 && ch <= 126) {
	snprintf(buf, szbuf, "'%c'", (char)ch);
    } else if (ch == '\a') {
	snprintf(buf, szbuf, "'\\a'");
    } else if (ch == '\b') {
	snprintf(buf, szbuf, "'\\b'");
    } else if (ch == '\f') {
	snprintf(buf, szbuf, "'\\f'");
    } else if (ch == '\n') {
	snprintf(buf, szbuf, "'\\n'");
    } else if (ch == '\r') {
	snprintf(buf, szbuf, "'\\r'");
    } else if (ch == '\t') {
	snprintf(buf, szbuf, "'\\t'");
    } else if (ch == '\v') {
	snprintf(buf, szbuf, "'\\v'");
    } else {
	snprintf(buf, szbuf, "%d", ch);
    }
    return buf;
}

static CcsBool_t
COS_Defines(CcOutputScheme_t * self, FILE * outfp, const char * indent)
{
    if (!self->globals->lexical.ignoreCase)
	fprintf(outfp, "%s#define CASE_SENSITIVE\n", indent);
    return TRUE;
}

static CcsBool_t
COS_Declarations(CcOutputScheme_t * self, FILE * outfp, const char * indent)
{
    fprintf(outfp, "%sself->eofSym = %d;\n", indent,
	    self->globals->syntax.eofSy->kind);
    fprintf(outfp, "%sself->maxT = %d;\n", indent,
	    self->globals->symtab.terminals.Count - 1);
    fprintf(outfp, "%sself->noSym = %d;\n", indent,
	    self->globals->syntax.noSy->kind);
    return TRUE;
}

static CcsBool_t
COS_Chars2States(CcOutputScheme_t * self, FILE * outfp, const char * indent)
{
    int numEle;
    CcLexical_StartTab_t * table, * cur;
    char buf0[8], buf1[8];
    fprintf(outfp, "%s{ EoF, EoF, -1 },\n", indent);
    table = CcLexical_GetStartTab(&self->globals->lexical, &numEle);
    for (cur = table; cur - table < numEle; ++cur)
	fprintf(outfp, "%s{ %d, %d, %d },\t/* %s %s */\n", indent,
		cur->keyFrom, cur->keyTo, cur->state,
		CharRepr(buf0, sizeof(buf0), cur->keyFrom),
		CharRepr(buf1, sizeof(buf1), cur->keyTo));
    CcFree(table);
    return TRUE;
}

static CcsBool_t
COS_Identifiers2KeywordKinds(CcOutputScheme_t * self, FILE * outfp,
			     const char * indent)
{
    int numEle;
    CcLexical_Identifier_t * list, * cur;

    list = CcLexical_GetIdentifiers(&self->globals->lexical, &numEle);
    for (cur = list; cur - list < numEle; ++cur)
	fprintf(outfp, "%s{ %s, %d },\n", indent, cur->name, cur->index);
    CcLexical_Identifiers_Destruct(list, numEle);
    return TRUE;
}

static CcsBool_t
COS_Comments(CcOutputScheme_t * self, FILE * outfp, const char * indent)
{
    const CcComment_t * cur;
    char buf0[8], buf1[8], buf2[8], buf3[8];
    for (cur = self->globals->lexical.firstComment; cur; cur = cur->next)
	fprintf(outfp, "%s    { { %s, %s }, { %s, %s }, %s },\n", indent,
		CharRepr(buf0, sizeof(buf0), cur->start[0]),
		CharRepr(buf1, sizeof(buf1), cur->start[1]),
		CharRepr(buf2, sizeof(buf2), cur->stop[0]),
		CharRepr(buf3, sizeof(buf3), cur->stop[1]),
		cur->nested ? "TRUE" : "FALSE");
    return TRUE;
}

static CcsBool_t
COS_Scan1(CcOutputScheme_t * self, FILE * outfp, const char * indent)
{
    const CcRange_t * curRange;
    char buf0[8], buf1[8];
    for (curRange = self->globals->lexical.ignored->head;
	 curRange; curRange = curRange->next) {
	if (curRange->from == curRange->to)
	    fprintf(outfp, "%s|| self->ch == %s\n", indent,
		    CharRepr(buf0 ,sizeof(buf0), curRange->from));
	else
	    fprintf(outfp, "%s|| (self->ch >= %s && self->ch <= %s)\n", indent,
		    CharRepr(buf0 ,sizeof(buf0), curRange->from),
		    CharRepr(buf1 ,sizeof(buf1), curRange->to));
    }
    return TRUE;
}

static void
COS_WriteState(CcOutputScheme_t * self, FILE * outfp, const char * indent,
	       const CcState_t * state, const CcBitArray_t * mask)
{
    const CcAction_t * action;
    CcCharSet_t * s; const CcRange_t * curRange;
    char buf0[8], buf1[8];
    int sIndex = state->base.index;

    if (CcBitArray_Get(mask, sIndex))
	fprintf(outfp, "%scase %d: case_%d:\n", indent, sIndex, sIndex);
    else
	fprintf(outfp, "%scase %d:\n", indent, sIndex);
    for (action = state->firstAction; action != NULL; action = action->next) {
	if (action == state->firstAction) fprintf(outfp, "%s    if (", indent);
	else fprintf(outfp, "%s    } else if (", indent);
	s = CcTransition_GetCharSet(&action->trans);
	for (curRange = s->head; curRange; curRange = curRange->next) {
	    if (curRange != s->head) fprintf(outfp, "%s        ", indent);
	    if (curRange->from == curRange->to)
		fprintf(outfp, "self->ch == %s",
			CharRepr(buf0, sizeof(buf0), curRange->from));
	    else
		fprintf(outfp, "(self->ch >= %s && self->ch <= %s)",
			CharRepr(buf0, sizeof(buf0), curRange->from),
			CharRepr(buf1, sizeof(buf1), curRange->to));
	    if (curRange->next) fprintf(outfp, " ||\n");
	}
	fprintf(outfp, ") {\n");
	fprintf(outfp, "%s        CcsScanner_GetCh(self); goto case_%d;\n",
		indent, action->target->state->base.index);
	CcCharSet_Destruct(s);
    }
    if (state->firstAction == NULL) fprintf(outfp, "%s    { ", indent);
    else fprintf(outfp, "%s    } else { ", indent);
    if (state->endOf == NULL) {
	fprintf(outfp, "kind = self->noSym;");
    } else if (CcSymbol_GetTokenKind(state->endOf) != symbol_classLitToken) {
	fprintf(outfp, "kind = %d;", state->endOf->kind);
    } else {
	fprintf(outfp,
		"kind = CcsScanner_GetKWKind(self, pos, self->pos, %d);",
		state->endOf->kind);
    }
    fprintf(outfp, " break; }\n");
}

static CcsBool_t
COS_Scan3(CcOutputScheme_t * self, FILE * outfp, const char * indent)
{
    CcArrayListIter_t iter;
    CcBitArray_t mask;
    const CcState_t * state;
    CcArrayList_t * stateArr = &self->globals->lexical.states;

    CcLexical_TargetStates(&self->globals->lexical, &mask);
    state = (CcState_t *)CcArrayList_First(stateArr, &iter);
    for (state = (const CcState_t *)CcArrayList_Next(stateArr, &iter);
	 state; state = (const CcState_t *)CcArrayList_Next(stateArr, &iter))
	COS_WriteState(self, outfp, indent, state, &mask);
    CcBitArray_Destruct(&mask);
    return TRUE;
}

static CcsBool_t
COS_Pragmas(CcOutputScheme_t * self, FILE * outfp, const char * indent)
{
    CcArrayListIter_t iter;
    const CcSymbolPR_t * sym, * sym1;
    const CcArrayList_t * pragmas = &self->globals->symtab.pragmas;

    for (sym = sym1 = (const CcSymbolPR_t *)CcArrayList_FirstC(pragmas, &iter);
	 sym; sym = (const CcSymbolPR_t *)CcArrayList_NextC(pragmas, &iter)) {
	fprintf(outfp, "%s%sif (self->la->kind == %d) {\n",
		indent, (sym == sym1) ? "" : "} else ", sym->base.kind);
	fprintf(outfp, "%s    ", indent);
	CcCopySourcePart(outfp, indent,
			 sym->semPos->col + 4, sym->semPos->text);
    }
    if (sym1) fprintf(outfp, "%s}\n", indent);
    return TRUE;
}

static CcsBool_t
COS_ProductionsHeader(CcOutputScheme_t * self,
		      FILE * outfp, const char * indent)
{
    CcArrayListIter_t iter;
    const CcSymbol_t * sym;
    const CcArrayList_t * nonterminals = &self->globals->symtab.nonterminals;

    for (sym = (const CcSymbol_t *)CcArrayList_FirstC(nonterminals, &iter);
	 sym; sym = (const CcSymbol_t *)CcArrayList_NextC(nonterminals, &iter))
	fprintf(outfp, "%sstatic void CcsParser_%s(CcsParser_t * self);\n",
		indent, sym->name);
    return TRUE;
}

static CcsBool_t
COS_ParseRoot(CcOutputScheme_t * self, FILE * outfp, const char * indent)
{
    fprintf(outfp, "%sCcsParser_%s(self);\n",
	    indent, self->globals->syntax.gramSy->name);
    return TRUE;
}

static void
SCOS_GenCond(CcOutputScheme_t * self, FILE * outfp, const char * indent,
	     const CcBitArray_t * s, const CcNode_t * p)
{
    const CcNodeRSLV_t * prslv; int n;
    CcArrayListIter_t iter; const CcSymbol_t * sym;
    const CcArrayList_t * terminals;
    CcCOutputScheme_t * ccself = (CcCOutputScheme_t *)self;

    if (p->base.type == node_rslv) {
	prslv = (CcNodeRSLV_t *)p;
	CcCopySourcePart(outfp, indent, prslv->pos->col, prslv->pos->text);
    } else if ((n = CcBitArray_Elements(s)) == 0) {
	fprintf(outfp, "FALSE");
    } else if (n <= maxTerm) {
	terminals = &self->globals->symtab.terminals;
	for (sym = (const CcSymbol_t *)CcArrayList_FirstC(terminals, &iter);
	     sym; sym = (const CcSymbol_t *)CcArrayList_NextC(terminals, &iter))
	    if (CcBitArray_Get(s, sym->kind)) {
		fprintf(outfp, "self->la->kind == %d", sym->kind);
		if (--n > 0) fprintf(outfp, " || ");
	    }
    } else {
	fprintf(outfp, "CcsParser_StartOf(%d)",
		CcSyntaxSymSet_New(&ccself->symSet, s));
    }
}

static void
SCOS_GenCode(CcOutputScheme_t * self, FILE * outfp, const char * indent,
	     CcNode_t * p, const CcBitArray_t * IsChecked)
{
    int err;
    CcNode_t * p2; CcBitArray_t s1, s2;
    CcNodeNT_t * pnt; CcNodeT_t * pt; CcNodeWT_t * pwt;
    CcNodeSEM_t * psem; CcNodeSYNC_t * psync;
    CcSyntax_t * syntax = &self->globals->syntax;
    CcCOutputScheme_t * ccself = (CcCOutputScheme_t *)self;

    while (p != NULL) {
	if (p->base.type == node_nt) {
	    pnt = (CcNodeNT_t *)p;
	    fprintf(outfp, "%s%s(", indent, pnt->sym->name);
	    CcCopySourcePart(outfp, indent, pnt->pos->col, pnt->pos->text);
	    fprintf(outfp, ");");
	} else if (p->base.type == node_t) {
	    pt = (CcNodeT_t *)p;
	    if (CcBitArray_Get(IsChecked, pt->sym->kind))
		fprintf(outfp, "%sCcsParser_Get(self);\n", indent);
	    else
		fprintf(outfp, "%sCcsParser_Expect(self, %d);\n",
			indent, pt->sym->kind);
	} else if (p->base.type == node_wt) {
	    pwt = (CcNodeWT_t *)p;
	    CcSyntax_Expected(syntax, &s1, p->next, ccself->curSy);
	    CcBitArray_Or(&s1, syntax->allSyncSets);
	    fprintf(outfp, "%sCcsParser_ExpecteWeak(self, %d, %d);\n",
		    indent, pwt->sym->kind,
		    CcSyntaxSymSet_New(&ccself->symSet, &s1));
	    CcBitArray_Destruct(&s1);
	} else if (p->base.type == node_any) {
	    fprintf(outfp, "%sCcsParser_Get(self);\n", indent);
	} else if (p->base.type == node_eps) {
	} else if (p->base.type == node_rslv) {
	} else if (p->base.type == node_sem) {
	    psem = (CcNodeSEM_t *)p;
	    CcCopySourcePart(outfp, indent, psem->pos->col, psem->pos->text);
	} else if (p->base.type == node_sync) {
	    psync = (CcNodeSYNC_t *)p;
	    err = CcSyntax_SyncError(syntax, ccself->curSy);
	    CcBitArray_Clone(&s1, psync->set);
	    fprintf(outfp, "%swhile (!(", indent);
	    SCOS_GenCond(self, outfp, indent, &s1, p);
	    fprintf(outfp, ")) {\n");
	    fprintf(outfp,
		    "%s    CcsParser_SynErr(self, %d); CcsParser_Get(self);\n",
		    indent, err);
	    fprintf(outfp, "%s}\n", indent);
	    CcBitArray_Destruct(&s1);
	} else if (p->base.type == node_alt) {
	} else if (p->base.type == node_iter) {
	} else if (p->base.type == node_opt) {
	}
    }
}

static CcsBool_t
COS_ProductionsBody(CcOutputScheme_t * self, FILE * outfp, const char * indent)
{
    CcBitArray_t IsChecked;
    CcArrayListIter_t iter;
    const CcSymbolNT_t * sym;
    const CcArrayList_t * nonterminals = &self->globals->symtab.nonterminals;
    CcCOutputScheme_t * ccself = (CcCOutputScheme_t *)self;

    CcBitArray(&IsChecked, self->globals->symtab.terminals.Count);
    for (sym = (const CcSymbolNT_t *)CcArrayList_FirstC(nonterminals, &iter);
	 sym;
	 sym = (const CcSymbolNT_t *)CcArrayList_NextC(nonterminals, &iter)) {
	ccself->curSy = (const CcSymbol_t *)sym;
	if (sym->attrPos == NULL) {
	    fprintf(outfp, "%sstatic void CcsParser_%s(CcsParser_t * self)\n",
		    indent, sym->base.name);
	} else {
	    fprintf(outfp, "%sstatic void CcsParser_%s(CcsParser_t * self, ",
		    indent, sym->base.name);
	    CcCopySourcePart(outfp, indent,
			     sym->attrPos->col, sym->attrPos->text);
	    fprintf(outfp, ")\n");
	}
	fprintf(outfp, "%s{\n", indent);
	CcCopySourcePart(outfp, indent, sym->semPos->col, sym->semPos->text);
	SCOS_GenCode(self, outfp, indent, sym->graph, &IsChecked);
	fprintf(outfp, "%s}\n\n", indent);
    }
    CcBitArray_Destruct(&IsChecked);
    return TRUE;
}

static CcsBool_t
COS_SynErrors(CcOutputScheme_t * self, FILE * outfp, const char * indent)
{
    CcArrayListIter_t iter; char * str;
    const CcSyntaxError_t * synerr;
    const CcArrayList_t * errors = &self->globals->syntax.errors;
    for (synerr = (const CcSyntaxError_t *)CcArrayList_FirstC(errors, &iter);
	 synerr;
	 synerr = (const CcSyntaxError_t *)CcArrayList_NextC(errors, &iter)) {
	fprintf(outfp, "%scase %d: s = \"", indent, synerr->base.index);
	str = CcEscape(synerr->sym->name);
	switch (synerr->type) {
	case cet_t:
	    fprintf(outfp, "\\\"\" %s \"\\\" expected", str);
	    break;
	case cet_alt:
	    fprintf(outfp, "this symbol not expected in \\\"\" %s \"\\\"", str);
	    break;
	case cet_sync:
	    fprintf(outfp, "invalid \"\\\"\" %s \"\\\"", str);
	    break;
	}
	CcFree(str);
	fprintf(outfp, "\"; break;\n");
    }
    return TRUE;
}

static CcsBool_t
COS_InitSet(CcOutputScheme_t * self, FILE * outfp, const char * indent)
{
    char * setstr; int setlen, index;
    const CcBitArray_t * cur;
    CcCOutputScheme_t * ccself = (CcCOutputScheme_t *)self;

    setlen = self->globals->symtab.terminals.Count;
    setstr = CcMalloc(setlen + 1); setstr[setlen] = 0;
    for (cur = ccself->symSet.start; cur < ccself->symSet.used; ++cur) {
	CcsAssert(setlen == CcBitArray_getCount(cur));
	for (index = 0; index < setlen; ++index)
	    setstr[index] = CcBitArray_Get(cur, index) ? '*' : '.';
	fprintf(outfp, "%s\"%s\",\n", indent, setstr);
    }
    CcFree(setstr);
    return TRUE;
}

static CcsBool_t
CcCOutputScheme_write(CcOutputScheme_t * self, FILE * outfp,
		      const char * func, const char * param,
		      const char * indent)
{
    if (!strcmp(func, "defines")) {
	return COS_Defines(self, outfp, indent);
    } else if (!strcmp(func, "declarations")) {
	return COS_Declarations(self, outfp, indent);
    } else if (!strcmp(func, "chars2states")) {
	return COS_Chars2States(self, outfp, indent);
    } else if (!strcmp(func, "identifiers2keywordkinds")) {
	return COS_Identifiers2KeywordKinds(self, outfp, indent);
    } else if (!strcmp(func, "comments")) {
	return COS_Comments(self, outfp, indent);
    } else if (!strcmp(func, "scan1")) {
	return COS_Scan1(self, outfp, indent);
    } else if (!strcmp(func, "scan3")) {
	return COS_Scan3(self, outfp, indent);
    } else if (!strcmp(func, "Pragmas")) {
	return COS_Pragmas(self, outfp, indent);
    } else if (!strcmp(func, "ProductionsHeader")) {
	return COS_ProductionsHeader(self, outfp, indent);
    } else if (!strcmp(func, "ParseRoot")) {
	return COS_ParseRoot(self, outfp, indent);
    } else if (!strcmp(func, "ProductionsBody")) {
	return COS_ProductionsBody(self, outfp, indent);
    } else if (!strcmp(func, "SynErrors")) {
	return COS_SynErrors(self, outfp, indent);
    } else if (!strcmp(func, "InitSet")) {
	return COS_InitSet(self, outfp, indent);
    }
    fprintf(stderr, "Unknown section '%s' encountered.\n", func);
    return TRUE;
}

static void
CcCOutputScheme_Destruct(CcObject_t * self)
{
    CcCOutputScheme_t * ccself = (CcCOutputScheme_t *)self;
    CcSyntaxSymSet_Destruct(&ccself->symSet);
    CcOutputScheme_Destruct(self);
}

static const CcOutputSchemeType_t COutputSchemeType = {
    { sizeof(CcCOutputScheme_t), "COutputScheme", CcCOutputScheme_Destruct },
    CcCOutputScheme_OutputInfos, CcCOutputScheme_write
};

CcCOutputScheme_t *
CcCOutputScheme(CcGlobals_t * globals, CcArguments_t * arguments)
{
    CcCOutputScheme_t * self = (CcCOutputScheme_t *)
	CcOutputScheme(&COutputSchemeType, globals, arguments);
    CcSyntaxSymSet(&self->symSet);
    CcSyntaxSymSet_New(&self->symSet, self->base.globals->syntax.allSyncSets);
    return self;
}
