# -*- python -*-
# Author: Charles Wang <charlesw123456@gmail.com>
# License: GPLv2

Import('env')
Import('libobjs')

libobjs.extend(map(lambda src: env.Object(src),
                   ['CDefs.c', 'ErrorPool.c', 'Buffer.c', 'Token.c',
                    'Position.c', 'Scanner.c', 'Parser.c', 'XmlScanner.c',
                    'XmlParser.c', 'COutputScheme.c', 'XmlScanOper.c']))
