/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
#include  <stdio.h>
#include  <stdlib.h>
#include  "Node.h"
#include  "Symbol.h"
#include  "ArrayList.h"
#include  "Position.h"
#include  "CharClass.h"
#include  "Tab.h"

Node_t *
Node(Node_t * self, int typ, Symbol_t * sym, int line)
{
    self = CocoMalloc(sizeof(Node_t));
    self->n = 0;
    self->typ = typ;
    self->next = NULL;
    self->down = NULL;
    self->sub = NULL;
    self->up = FALSE;
    self->sym = sym;
    self->val = 0;
    self->code = 0;
    self->set = NULL;
    self->pos = NULL;
    self->line = line;
    self->state = NULL;
    return self;
}

void
Node_Destruct(Node_t * self)
{
}

Bool_t
Node_DelGraph(Node_t * self)
{
    return self == NULL || (Node_DelNode(self) && Node_DelGraph(self->next));
}

Bool_t
Node_DelSubGraph(Node_t * self)
{
    return self == NULL || (Node_DelNode(self) && Node_DelSubGraph(self->next));
}

Bool_t
Node_DelNode(Node_t * self)
{
    if (self->typ == node_nt) return self->sym->deletable;
    else if (self->typ == node_alt)
	return Node_DelSubGraph(self->sub) ||
	    (self->down != NULL && Node_DelSubGraph(self->down));
    return self->typ == node_iter || self->typ == node_opt ||
	self->typ == node_sem || self->typ == node_eps ||
	self->typ == node_rslv || self->typ == node_sync;
}

int
Node_Num(const Node_t * self)
{
    return self ? self->n : 0;
}

static int
Ptr(Node_t * self, Bool_t up)
{
    if (self == NULL) return 0;
    else if (up) return -(self->n);
    return self->n;
}

void
Node_Dump(const Node_t * self, DumpBuffer_t * buf, Tab_t * tab)
{
    char name[12]; CharClass_t * cc;
    DumpBuffer_Print(buf, "%4d %s ", self->n, nTyp[self->typ]);
    if (self->sym != NULL) {
	snprintf(name, sizeof(name), "%s            ", self->sym->name);
	DumpBuffer_Print(buf, "%12s ", name);
    } else if (self->typ == node_clas) {
	cc = (CharClass_t *)ArrayList_Get(&tab->classes, self->val);
	snprintf(name, sizeof(name), "%s            ", cc->name);
	DumpBuffer_Print(buf, "%12s ", name);
    } else {
	DumpBuffer_Print(buf, "             ");
    }
    DumpBuffer_Print(buf, "%5d ", Ptr(self->next, self->up));

    if (self->typ == node_t || self->typ == node_nt || self->typ == node_wt) {
	DumpBuffer_Print(buf, "             %5s",
			 Position_Dump(self->pos, name, sizeof(name)));
    } else if (self->typ == node_chr) {
	DumpBuffer_Print(buf, "%5d %5d       ", self->val, self->code);
    } else if (self->typ == node_clas) {
	DumpBuffer_Print(buf, "      %5d       ", self->code);
    } else if (self->typ == node_alt ||
	       self->typ == node_iter ||
	       self->typ == node_opt) {
	DumpBuffer_Print(buf, "%5d %5d       ",
			 Ptr(self->down, FALSE), Ptr(self->sub, FALSE));
    } else if (self->typ == node_sem) {
	DumpBuffer_Print(buf, "             %5s",
			 Position_Dump(self->pos, name, sizeof(name)));
    } else if (self->typ == node_eps ||
	       self->typ == node_any ||
	       self->typ == node_sync) {
	DumpBuffer_Print(buf, "                  ");
    }
    DumpBuffer_Print(buf, "%5d", self->line);
}
