/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
#ifndef  COCO_BITARRAY_H
#define  COCO_BITARRAY_H

#ifndef  COCO_DEFS_H
#include  "Defs.h"
#endif

EXTC_BEGIN

struct CsBitArray_s {
    int numbits;
    unsigned char * data;
};

CsBitArray_t * CsBitArray(CsBitArray_t * self, int numbits);
CsBitArray_t * CsBitArray1(CsBitArray_t * self, int numbits);
CsBitArray_t * CsBitArray_Clone(CsBitArray_t * self, const CsBitArray_t * value);
void CsBitArray_Destruct(CsBitArray_t * self);

/* Return -1 for error. */
int CsBitArray_getCount(const CsBitArray_t * self);
int CsBitArray_Elements(const CsBitArray_t * self);
CsBool_t CsBitArray_Get(const CsBitArray_t * self, int index);
void CsBitArray_Set(CsBitArray_t * self, int index, CsBool_t value);
void CsBitArray_SetAll(CsBitArray_t * self, CsBool_t value);
CsBool_t CsBitArray_Equal(const CsBitArray_t * self1, const CsBitArray_t * self2);
void CsBitArray_Not(CsBitArray_t * self);
int CsBitArray_And(CsBitArray_t * self, const CsBitArray_t * value);
int CsBitArray_Or(CsBitArray_t * self, const CsBitArray_t * value);
int CsBitArray_Xor(CsBitArray_t * self, const CsBitArray_t * value);
CsBool_t CsBitArray_Intersect(const CsBitArray_t * self1, const CsBitArray_t * self2);
void CsBitArray_Subtract(CsBitArray_t * self, const CsBitArray_t * b);

EXTC_END

#endif  /* COCO_BITARRAY_H */
