# -*- python -*-
# Author: Charles Wang <charlesw123456@gmail.com>
# License: GPLv2

import os.path

Import('env')
Import('cocosrc_libobjs')

cocosrc_libobjs.extend(map(lambda src: env.Object(src),
                           ['CSharpOutputScheme.c']))

SConscript(os.path.join('test', 'SConscript'))
