# -*- python -*-
# Author: Charles Wang <charlesw123456@gmail.com>
# License: GPLv2

Import('env', 'lib')

env.Program('AutoTests', ['AutoTests.c', 'TestBitArray.c', 'TestCharSet.c',
                          lib])
env.Program('TestScanner', ['TestScanner.c', lib])
env.Program('TestGlobals', ['TestGlobals.c', lib])
