/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
#include  "Globals.h"
#include  "c/CGlobals.h"

CcGlobals_t *
CcGlobals(CcGlobals_t * self, const char * fname, FILE * errfp)
{
    if (!CcsGlobals(&self->base, fname, errfp)) goto errquit0;
    if (!CcSymbolTable(&self->symtab)) goto errquit1;
    if (!CcLexical(&self->lexical, self)) goto errquit2;
    if (!CcSyntax(&self->syntax, self)) goto errquit3;
    return self;
 errquit3:
    CcLexical_Destruct(&self->lexical);
 errquit2:
    CcSymbolTable_Destruct(&self->symtab);
 errquit1:
    CcsGlobals_Destruct(&self->base);
 errquit0:
    return NULL;
}

void
CcGlobals_Destruct(CcGlobals_t * self)
{
    CcSyntax_Destruct(&self->syntax);
    CcLexical_Destruct(&self->lexical);
    CcSymbolTable_Destruct(&self->symtab);
    CcsGlobals_Destruct(&self->base);
}

void
CcGlobals_Parse(CcGlobals_t * self)
{
    CcsGlobals_Parse(&self->base);
    CcLexical_Finish(&self->lexical);
}
