/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
#include  "EBNF.h"
#include  "lexical/Nodes.h"
#include  "syntax/Nodes.h"
#include  "SymbolTable.h"

static void CcNodeAlt_Destruct(CcObject_t * self)
{
}
static const CcNodeType_t NodeAlt = {
    { sizeof(CcNode_t), "node_alt", CcNodeAlt_Destruct }
};
const CcNodeType_t * node_alt = &NodeAlt;

static void CcNodeIter_Destruct(CcObject_t * self)
{
}
static const CcNodeType_t NodeIter = {
    { sizeof(CcNode_t), "node_iter", CcNodeIter_Destruct }
};
const CcNodeType_t * node_iter = &NodeIter;

static void CcNodeOpt_Destruct(CcObject_t * self)
{
}
static const CcNodeType_t NodeOpt = {
    { sizeof(CcNode_t), "node_opt", CcNodeOpt_Destruct }
};
const CcNodeType_t * node_opt = &NodeOpt;

static void CcNodeEps_Destruct(CcObject_t * self)
{
}
static const CcNodeType_t NodeEps = {
    { sizeof(CcNode_t), "node_opt", CcNodeEps_Destruct }
};
const CcNodeType_t * node_eps = &NodeEps;

CcNode_t *
CcNode(const CcNodeType_t * type, int n)
{
    CcNode_t * self = (CcNode_t *)CcObject(&type->base);
    memset(self, 0, type->base.size);
    self->n = n;
    return self;
}

CcNode_t *
CcNode_NewWithSub(const CcNodeType_t * type, int n, CcNode_t * sub)
{
    CcNode_t * self = (CcNode_t *)CcObject(&type->base);
    self->n = n;
    self->sub = sub;
    return self;
}

void
CcNode_Destruct(CcNode_t * self)
{
    CcObject_Destruct(&self->base);
}

CcGraph_t *
CcGraph(void)
{
    CcGraph_t * self = CcMalloc(sizeof(CcGraph_t));
    self->l = self->r = NULL;
    return self;
}

CcGraph_t *
CcGraphP(CcNode_t * p)
{
    CcGraph_t * self = CcMalloc(sizeof(CcGraph_t));
    self->l = self->r = p;
    return self;
}

void
CcGraph_Destruct(CcGraph_t * self)
{
    CcFree(self);
}

CcsBool_t
CcNode_DelGraph(CcNode_t * self)
{
    return self == NULL ||
	(CcNode_DelNode(self) && CcNode_DelGraph(self->next));
}

CcsBool_t
CcNode_DelSubGraph(CcNode_t * self)
{
    return self == NULL ||
	(CcNode_DelNode(self) && CcNode_DelSubGraph(self->next));
}

CcsBool_t
CcNode_DelNode(CcNode_t * self)
{
    const CcNodeType_t * type = (const CcNodeType_t *)self->base.type;
    /* In fact, the check of the deletablity of a node should be placed in
     * a virtual function, I just write all of them here for convenience.
     * This way include some extra dependencies, may be I shall fix it
     * in future. */
    if (type == node_nt) {
	CcNodeNT_t * p0 = (CcNodeNT_t *)self;
	CcSymbolNT_t * sym = (CcSymbolNT_t *)p0->sym;
	return sym->deletable;
    } else if (type == node_alt) {
	return CcNode_DelSubGraph(self->sub) ||
	    (self->down != NULL && CcNode_DelSubGraph(self->down));
    }
    return type == node_iter || type == node_opt || type == node_sem ||
	type == node_eps || type == node_rslv || type == node_sync;
}

CcNode_t *
CcGraph_MakeFirstAlt(CcGraph_t * self, int n)
{
    self->l = CcNode_NewWithSub(node_alt, n, self->l);
    self->l->line = self->l->sub->line;
    self->l->next = self->r;
    self->r = self->l;
    return self->l;
}

CcNode_t *
CcGraph_MakeAlternative(CcGraph_t * self, CcGraph_t * g2, int n)
{
    CcNode_t * p;
    g2->l = CcNode_NewWithSub(node_alt, n, g2->l);
    g2->l->line = g2->l->sub->line;
    p = self->l; while (p->down != NULL) p = p->down;
    p->down = g2->l;
    p = self->r; while (p->next != NULL) p = p->next;
    /* Append alternative to self end list. */
    p->next = g2->l;
    /* Append g2 end list to self end list. */
    g2->l->next = g2->r;
    return g2->l;
}

void
CcGraph_MakeSequence(CcGraph_t * self, CcGraph_t * g2)
{
    CcNode_t * q, * p;
    p = self->r->next; self->r->next = g2->l; /* link head node */
    while (p != NULL) { /* link substructure */
	q = p->next; p->next = g2->l; p->up = TRUE;
	p = q;
    }
    self->r = g2->r;
}

CcNode_t *
CcGraph_MakeIteration(CcGraph_t * self, int n)
{
    CcNode_t * p , * q;
    self->l = CcNode_NewWithSub(node_iter, n, self->l);
    p = self->r;
    self->r = self->l;
    while (p != NULL) {
	q = p->next; p->next = self->l; p->up = TRUE;
	p = q;
    }
    return self->l;
}

CcNode_t *
CcGraph_MakeOption(CcGraph_t * self, int n)
{
    self->l = CcNode_NewWithSub(node_opt, n, self->l);
    self->l->next = self->r;
    self->r = self->l;
    return self->l;
}

void
CcGraph_Finish(CcGraph_t * self)
{
    CcNode_t * p, * q;
    p = self->r;
    while (p != NULL) {
	q = p->next; p->next = NULL; p = q;
    }
}
