/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
#include  "SymbolTable.h"
#include  "Symbols.h"

CcSymbolTable_t *
CcSymbolTable(CcSymbolTable_t * self)
{
    CcArrayList(&self->terminals);
    CcArrayList(&self->nonterminals);
    CcArrayList(&self->pragmas);
    return self;
}

void
CcSymbolTable_Destruct(CcSymbolTable_t * self)
{
    CcArrayList_Destruct(&self->nonterminals);
    CcArrayList_Destruct(&self->terminals);
    CcArrayList_Destruct(&self->pragmas);
}

CcSymbol_t *
CcSymbolTable_NewTerminal(CcSymbolTable_t * self, const char * name, int line)
{
    char * name0 = CcUnescape(name);
    CcObject_t * sym = CcArrayList_New(&self->terminals,
				       (CcObject_t *)CcSymbolT(name0, line));
    CcFree(name0);
    return (CcSymbol_t *)sym;
}

CcSymbol_t *
CcSymbolTable_NewPragma(CcSymbolTable_t * self, const char * name, int line)
{
    char * name0 = CcUnescape(name);
    CcObject_t * sym = CcArrayList_New(&self->pragmas,
				       (CcObject_t *)CcSymbolPR(name, line));
    CcFree(name0);
    return (CcSymbol_t *)sym;
}

CcSymbol_t *
CcSymbolTable_NewNonTerminal(CcSymbolTable_t * self,
			     const char * name, int line)
{
    char * name0 = CcUnescape(name);
    CcObject_t * sym = CcArrayList_New(&self->nonterminals,
				       (CcObject_t *)CcSymbolNT(name, line));
    CcFree(name0);
    return (CcSymbol_t *)sym;
}

CcSymbol_t *
CcSymbolTable_FindSym(CcSymbolTable_t * self, const char * name)
{
    CcArrayListIter_t iter; CcSymbol_t * sym;
    char * name0 = CcUnescape(name);
    for (sym = (CcSymbol_t *)CcArrayList_First(&self->terminals, &iter);
	 sym; sym = (CcSymbol_t *)CcArrayList_Next(&self->terminals, &iter))
	if (!strcmp(sym->name, name0)) goto found;
    for (sym = (CcSymbol_t *)CcArrayList_First(&self->nonterminals, &iter);
	 sym; sym = (CcSymbol_t *)CcArrayList_Next(&self->nonterminals, &iter))
	if (!strcmp(sym->name, name0)) goto found;
    CcFree(name0);
    return NULL;
 found:
    CcFree(name0);
    return sym;
}
