/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
#include  "XmlSpecMap.h"
#include  "XmlSpec.h"

#define  SZ_XMLSPECMAP  127

CcXmlSpecMap_t *
CcXmlSpecMap(CcXmlSpecMap_t * self, CcGlobals_t * globals)
{
    self->globals = globals;
    CcArrayList(&self->storage);
    CcHashTable(&self->map, SZ_XMLSPECMAP);
    return self;
}

void
CcXmlSpecMap_Destruct(CcXmlSpecMap_t * self)
{
    CcHashTable_Destruct(&self->map);
    CcArrayList_Destruct(&self->storage);
}

CcsBool_t
CcXmlSpecMap_Add(CcXmlSpecMap_t * self, const char * nsURI, CcXmlSpec_t * xmlspec)
{
    if (CcHashTable_Get(&self->map, nsURI)) return FALSE;
    xmlspec = (CcXmlSpec_t *)
	CcArrayList_New(&self->storage, (CcObject_t *)xmlspec);
    CcHashTable_Set(&self->map, nsURI, (CcObject_t *)xmlspec);
    return TRUE;
}

void
CcXmlSpecMap_MakeTerminals(const CcXmlSpecMap_t * self, CcGlobals_t * globals)
{
    CcArrayListIter_t iter; const CcXmlSpec_t * xmlspec;

    for (xmlspec = (const CcXmlSpec_t *)CcArrayList_FirstC(&self->storage, &iter);
	 xmlspec; xmlspec = (const CcXmlSpec_t *)CcArrayList_NextC(&self->storage, &iter))
	CcXmlSpec_MakeTerminals(xmlspec, globals);
}

CcsBool_t
CcXmlSpecMap_Finish(CcXmlSpecMap_t * self)
{
    CcXmlSpecMap_MakeTerminals(self, self->globals);
    return TRUE;
}
