/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
#include  "EBNF.h"

static const CcNodeType_t NodeAlt = {
    { sizeof(CcNode_t), "alt" }
};
const CcNodeType_t * node_alt = &NodeAlt;

static const CcNodeType_t NodeIter = {
    { sizeof(CcNode_t), "iter" }
};
const CcNodeType_t * node_iter = &NodeIter;

static const CcNodeType_t NodeOpt = {
    { sizeof(CcNode_t), "opt" }
};
const CcNodeType_t * node_opt = &NodeOpt;

CcNode_t *
CcNode_NewWithSub(CcNode_t * self, const CcNodeType_t * type, CcNode_t * sub)
{
    self = (CcNode_t *)CcObject(self ? &self->base : NULL, &type->base);
    self->sub = sub;
    return self;
}

void
CcNode_Destruct(CcNode_t * self)
{
    CcObject_Destruct(&self->base);
}

CcGraph_t *
CcGraph(CcGraph_t * self)
{
    self = AllocObject(self, sizeof(CcGraph_t));
    self->l = self->r = NULL;
    return self;
}

CcGraph_t *
CcGraphP(CcGraph_t * self, CcNode_t * p)
{
    self = AllocObject(self, sizeof(CcGraph_t));
    self->l = self->r = p;
    return self;
}

void
CcGraph_Destruct(CcGraph_t * self)
{
    CcFree(self);
}

void
CcGraph_MakeFirstAlt(CcGraph_t * self)
{
    self->l = CcNode_NewWithSub(NULL, node_alt, self->l);
    self->l->line = self->l->sub->line;
    self->l->next = self->r;
    self->r = self->l;
}

void
CcGraph_MakeAlternative(CcGraph_t * self, CcGraph_t * g2)
{
    CcNode_t * p;
    g2->l = CcNode_NewWithSub(NULL, node_alt, g2->l); g2->l->line = g2->l->sub->line;
    p = self->l; while (p->down != NULL) p = p->down;
    p->down = g2->l;
    p = self->r; while (p->next != NULL) p = p->next;
    /* Append alternative to self end list. */
    p->next = g2->l;
    /* Append g2 end list to self end list. */
    g2->l->next = g2->r;
}

void
CcGraph_MakeSequence(CcGraph_t * self, CcGraph_t * g2)
{
    CcNode_t * q, * p;
    p = self->r->next; self->r->next = g2->l; /* link head node */
    while (p != NULL) { /* link substructure */
	q = p->next; p->next = g2->l; p->up = TRUE;
	p = q;
    }
    self->r = g2->r;
}

void
CcGraph_MakeIteration(CcGraph_t * self)
{
    CcNode_t * p , * q;
    self->l = CcNode_NewWithSub(NULL, node_iter, self->l);
    p = self->r;
    self->r = self->l;
    while (p != NULL) {
	q = p->next; p->next = self->l; p->up = TRUE;
	p = q;
    }
}

void
CcGraph_MakeOption(CcGraph_t * self)
{
    self->l = CcNode_NewWithSub(NULL, node_opt, self->l);
    self->l->next = self->r;
    self->r = self->l;
}

void
CcGraph_Finish(CcGraph_t * self)
{
    CcNode_t * p, * q;
    p = self->r;
    while (p != NULL) {
	q = p->next; p->next = NULL; p = q;
    }
}
