/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
#include  "SymbolTable.h"

static const CcSymbolType_t SymbolT = {
    { sizeof(CcSymbolT_t), "symbol_t" }
};
const CcSymbolType_t * symbol_t = &SymbolT;

static const CcSymbolType_t SymbolNT = {
    { sizeof(CcSymbolNT_t), "symbol_nt" }
};
const CcSymbolType_t * symbol_nt = &SymbolNT;

static const CcSymbolType_t SymbolPR = {
    { sizeof(CcSymbolPR_t), "symbol_pr" }
};
const CcSymbolType_t * symbol_pr = &SymbolPR;

static const CcSymbolType_t SymbolUNKNOWN = {
    { sizeof(CcSymbolPR_t), "symbol_unknown" }
};
const CcSymbolType_t * symbol_unknown = &SymbolUNKNOWN;

static const CcSymbolType_t SymbolRSLV = {
    { sizeof(CcSymbolPR_t), "symbol_rslv" }
};
const CcSymbolType_t * symbol_rslv = &SymbolRSLV;

CcSymbolTable_t *
CcSymbolTable(CcSymbolTable_t * self)
{
    CcArrayList(&self->terminals);
    CcArrayList(&self->pragmas);
    CcArrayList(&self->nonterminals);
    return self;
}

void
CcSymbolTable_Destruct(CcSymbolTable_t * self)
{
    CcArrayList_Destruct(&self->nonterminals);
    CcArrayList_Destruct(&self->pragmas);
    CcArrayList_Destruct(&self->terminals);
}

CcSymbol_t *
CcSymbolTable_NewTerminal(CcSymbolTable_t * self, const char * name, int line)
{

}

CcSymbol_t *
CcSymbolTable_NewNonTerminal(CcSymbolTable_t * self,
			     const char * name, int line)
{
}

CcSymbol_t *
CcSymbolTable_Pragma(CcSymbolTable_t * self, const char * name, int line)
{
}
