# -*- python -*-
# Author: Charles Wang <charlesw123456@gmail.com>
# License: GPLv2.
import os.path

Import('env')
Import('CocoXmlExe')
Import('XmlScannerFrame', 'XmlParserFrame')

env.CLIProgram('samples', ['Main.cs', 'RSSData.cs', 'XmlScanner.cs', 'XmlParser.cs'])
env.Command(['XmlScanner.cs', 'XmlParser.cs'], [CocoXmlExe, 'rss.atg'],
            'mono ${SOURCES[0]} -frames ${SOURCES[0].srcdir} ${SOURCES[1]}')
env.Depends('XmlScanner.cs', XmlScannerFrame)
env.Depends('XmlParser.cs', XmlParserFrame)
