# -*- python -*-
# Author: Charles Wang <charlesw123456@gmail.com>
# License: GPLv2

Import('env')
Import('libobjs')
Import('cocosrc_libobjs')

if  'expat' in env['COCO_FEATURES']:
    libobjs.extend(map(lambda src: env.Object(src), ['XmlScanOper.c']))
cocosrc_libobjs.extend(map(lambda src: env.Object(src),
                           ['Scanner.c', 'Parser.c', 'CXmlOutputScheme.c']))
