# -*- python -*-
# Author: Charles Wang <charlesw123456@gmail.com>
# License: GPLv2

Import('env', 'lib', 'cocoexe')

targets = ['Scanner.h', 'Scanner.c', 'Parser.h', 'Parser.c']
env.Command(targets, ['CExpr.atg'], '"%s" -g $SOURCES' % str(cocoexe[0]))
env.Depends(targets, cocoexe)
env.Program('TestCExpr', ['main.c', 'Parser.c', 'Scanner.c', lib])
