# -*- python -*-
# Author: Charles Wang <charlesw123456@gmail.com>
# License: GPLv2

Import('env', 'lib', 'cocoexe')

env.Command(['Scanner.h', 'Scanner.c', 'Parser.h', 'Parser.c'],
            'CExpr.atg', '%s $SOURCES' % str(cocoexe[0]))
env.Program('TestCExpr', ['main.c', 'Parser.c', 'Scanner.c', lib])
