/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
#include  <stdlib.h>
#include  <string.h>
#include  "Action.h"
#include  "CharClass.h"
#include  "CharSet.h"
#include  "Target.h"
#include  "State.h"
#include  "Tab.h"

Action_t *
Action(Action_t * self, int typ, int sym, int tc)
{
    if (!self && !(self = malloc(sizeof(Action_t)))) return NULL;
    self->typ = typ;
    self->sym = sym;
    self->tc = tc;
    self->target = NULL;
    self->next = NULL;
    return self;
}

void
Action_Destruct(Action_t * self)
{
}

void
Action_AddTarget(Action_t * self, Target_t * t)
{
    Target_t * last = NULL;
    Target_t * p = self->target;
    while (p != NULL && t->state->nr >= p->state->nr) {
	if (t->state == p->state) return;
	last = p; p = p->next;
    }
    t->next = p;
    if (p == self->target)  self->target = t;
    else  last->next = t;
}

int
Action_AddTargets(Action_t * self, Action_t * a)
{
    Target_t * p, * t;
    for (p = a->target; p != NULL; p = p->next) {
	if (!(t = Target(NULL, p->state))) return -1;
	Action_AddTarget(self, t);
    }
    if (a->tc == node_contextTrans) self->tc = node_contextTrans;
    return 0;
}

CharSet_t *
Action_Symbols(Action_t * self, Tab_t * tab)
{
    CharSet_t * s;
    if (self->typ == node_clas) {
	s = CharSet_Clone(NULL, Tab_CharClassSet(tab, self->sym));
    } else {
	if ((s = CharSet(NULL))) {
	    if (CharSet_Set(s, self->sym) < 0) {
		CharSet_Destruct(s); free(s);
		return NULL;
	    }
	}
    }
    return s;
}

void
Action_ShiftWith(Action_t * self, CharSet_t * s, Tab_t * tab)
{
    CharClass_t * c;
    if (CharSet_Elements(s) == 1) {
	self->typ = node_chr; self->sym = CharSet_First(s);
    } else {
	c = Tab_FindCharClassC(tab, s);
	if (c == NULL) c = Tab_NewCharClass(tab, "#", s);
	self->typ = node_clas; self->sym = c->n;
    }
}
