/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
#include  <stdarg.h>
#include  <stdio.h>
#include  <stdlib.h>
#include  <string.h>
#include  "Defs.h"

void *
_CocoMalloc_(size_t size, const char * fname, int line)
{
    void * ptr;
    if ((ptr = malloc(size))) return ptr;
    fprintf(stderr, "malloc failed in %s#%d!\n", fname, line);
    exit(-1);
}

void *
_CocoRealloc_(void * ptr, size_t size, const char * fname, int line)
{
    if ((ptr = realloc(ptr, size))) return ptr;
    fprintf(stderr, "realloc failed in %s#%d!\n", fname, line);
    exit(-1);
}

void
_CocoFree_(void * ptr, const char * fname, int line)
{
    free(ptr);
}

char *
_CocoStrdup_(const char * str, const char * fname, int line)
{
    char * ptr;
    if ((ptr = strdup(str))) return ptr;
    fprintf(stderr, "strdup failed in %s#%d!", fname, line);
    exit(-1);
}

void *
_AllocObject_(void * self, size_t szobj, const char * fname, int line)
{
    if (self) return self;
    return _CocoMalloc_(szobj, fname, line);
}

void
DumpBuffer(DumpBuffer_t * self, char * buf, size_t szbuf)
{
    self->start = buf;
    self->cur = self->start; *self->cur = 0;
    self->last = buf + szbuf;
}

void
DumpBuffer_Print(DumpBuffer_t * self, const char * format, ...)
{
    va_list ap;

    va_start(ap, format);
    self->cur += vsnprintf(self->cur, self->last - self->cur, format, ap);
    va_end(ap);
}

Bool_t
DumpBuffer_Full(DumpBuffer_t * self)
{
    return self->cur == self->last;
}

void
Unescape(DumpBuffer_t * buf, const char * s)
{
}

void
EscapeCh(DumpBuffer_t * buf, int ch)
{
    switch (ch) {
    case '\\': DumpBuffer_Print(buf, "\\\\"); break;
    case '\'': DumpBuffer_Print(buf, "\\'"); break;
    case '\"': DumpBuffer_Print(buf, "\\\""); break;
    case '\t': DumpBuffer_Print(buf, "\\t"); break;
    case '\r': DumpBuffer_Print(buf, "\\r"); break;
    case '\n': DumpBuffer_Print(buf, "\\n"); break;
    default:
	if (ch < ' ' || ch > 127) DumpBuffer_Print(buf, "%%%02X", ch);
	else DumpBuffer_Print(buf, "%c", ch);
	break;
    }
}

void
Escape(DumpBuffer_t * buf, const char * s)
{
    while (*s && !DumpBuffer_Full(buf)) EscapeCh(buf, *s);
}

const char * nTyp[] = {
    "    ", "t   ", "pr  ", "nt  ", "clas", "chr ", "wt  ", "any ", "eps ",
    "sync", "sem ", "alt ", "iter", "opt ", "rslv"
};
