/* -*- c -*- */
/*---- open(Scanner.h) S ----*/
/*---- open(c.Scanner.frame) F ----*/
/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
/*---- enable ----*/
#ifndef  COCO_SCANNER_H
#define  COCO_SCANNER_H

#include  <stdio.h>

#ifdef __cplusplus
#define  EXTC_BEGIN extern "C" {
#define  EXTC_END   }
#else
#define  EXTC_BEGIN
#define  EXTC_END
#endif

EXTC_BEGIN

typedef struct Token_s Token_t;
struct Token_s
{
    int kind;
    int pos;
    int col;
    int line;
    char * val;
    Token_t * next;
};

Token_t * Token(Token_t * self);
void Token_Destruct(Token_t * self);

typedef struct Buffer_s Buffer_t;
struct Buffer_s {
    char * buf;
    char * cur;
    char * last;
};

Buffer_t * Buffer(Buffer_t * self, FILE * fp);
void Buffer_Destruct(Buffer_t * self);
int Buffer_Read(Buffer_t * self);
int Buffer_Peek(Buffer_t * self);
const char * Buffer_GetString(Buffer_t * self, int start);
int Buffer_GetPos(Buffer_t * self);
void Buffer_SetPos(Buffer_t * self, int pos);

EXTC_END

#endif /* COCO_SCANNER_H */
