/*-------------------------------------------------------------------------
  Author (C) 2008, Charles Wang <charlesw123456@gmail.com>

  This program is free software; you can redistribute it and/or modify it 
  under the terms of the GNU General Public License as published by the 
  Free Software Foundation; either version 2, or (at your option) any 
  later version.

  This program is distributed in the hope that it will be useful, but 
  WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY 
  or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
  for more details.

  You should have received a copy of the GNU General Public License along 
  with this program; if not, write to the Free Software Foundation, Inc., 
  59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

  As an exception, it is allowed to write an extension of Coco/R that is
  used as a plugin in non-free software.

  If not otherwise stated, any source code generated by Coco/R (other than 
  Coco/R itself) does not fall under the GNU General Public License.
-------------------------------------------------------------------------*/
#include  "syntax/Nodes.h"

static void
CcNodeT_Construct(CcObject_t * self, va_list ap)
{
    CcNodeT_t * ccself = (CcNodeT_t *)self;
    ccself->sym = va_arg(ap, CcSymbol_t *);
    ccself->pos = va_arg(ap, CcsPosition_t *);
}
static void
CcNodeT_Destruct(CcObject_t * self)
{
    CcNodeT_t * ccself = (CcNodeT_t *)self;
    if (ccself->pos) CcsPosition_Destruct(ccself->pos);
    CcNode_Destruct(self);
}
static const CcNodeType_t NodeT = {
    { sizeof(CcNodeT_t), "node_t", CcNodeT_Construct, CcNodeT_Destruct },
    CcNode_NoDeletable
};
const CcObjectType_t * node_t = (const CcObjectType_t *)&NodeT;

static const CcNodeType_t NodePR = {
    { sizeof(CcNodePR_t), "node_pr", CcNode_Construct, CcNode_Destruct },
    CcNode_NoDeletable
};
const CcObjectType_t * node_pr = (const CcObjectType_t *)&NodePR;

static void
CcNodeNT_Construct(CcObject_t * self, va_list ap)
{
    CcNodeNT_t * ccself = (CcNodeNT_t *)self;
    ccself->sym = va_arg(ap, CcSymbol_t *);
    ccself->pos = va_arg(ap, CcsPosition_t *);
}
static void
CcNodeNT_Destruct(CcObject_t * self)
{
    CcNodeNT_t * ccself = (CcNodeNT_t *)self;
    if (ccself->pos) CcsPosition_Destruct(ccself->pos);
    CcNode_Destruct(self);
}
static const CcNodeType_t NodeNT = {
    { sizeof(CcNodeNT_t), "node_nt", CcNodeNT_Construct, CcNodeNT_Destruct },
    CcNode_NoDeletable
};
const CcObjectType_t * node_nt = (const CcObjectType_t *)&NodeNT;

static void
CcNodeWT_Construct(CcObject_t * self, va_list ap)
{
    CcNodeWT_t * ccself = (CcNodeWT_t *)self;
    ccself->sym = va_arg(ap, CcSymbol_t *);
    ccself->pos = va_arg(ap, CcsPosition_t *);
}
static void
CcNodeWT_Destruct(CcObject_t * self)
{
    CcNodeWT_t * ccself = (CcNodeWT_t *)self;
    if (ccself->pos) CcsPosition_Destruct(ccself->pos);
    CcNode_Destruct(self);
}
static const CcNodeType_t NodeWT = {
    { sizeof(CcNodeWT_t), "node_wt", CcNodeWT_Construct, CcNodeWT_Destruct },
    CcNode_NoDeletable
};
const CcObjectType_t * node_wt = (const CcObjectType_t *)&NodeWT;

static void
CcNodeANY_Construct(CcObject_t * self, va_list ap)
{
    CcNodeANY_t * ccself = (CcNodeANY_t *)self;
    ccself->set = NULL;
}
static void
CcNodeANY_Destruct(CcObject_t * self)
{
    CcNodeANY_t * ccself = (CcNodeANY_t *)self;
    if (ccself->set) CcBitArray_Destruct(ccself->set);
    CcNode_Destruct(self);
}
static const CcNodeType_t NodeANY = {
    { sizeof(CcNodeANY_t), "node_any", CcNodeANY_Construct, CcNodeANY_Destruct },
    CcNode_NoDeletable
};
const CcObjectType_t * node_any = (const CcObjectType_t *)&NodeANY;

static void
CcNodeSYNC_Construct(CcObject_t * self, va_list ap)
{
    CcNodeSYNC_t * ccself = (CcNodeSYNC_t *)self;
    ccself->set = NULL;
}
static void
CcNodeSYNC_Destruct(CcObject_t * self)
{
    CcNodeSYNC_t * ccself = (CcNodeSYNC_t *)self;
    if (ccself->set) CcBitArray_Destruct(ccself->set);
    CcNode_Destruct(self);
}
static const CcNodeType_t NodeSYNC = {
    { sizeof(CcNodeSYNC_t), "node_sync", CcNodeSYNC_Construct, CcNodeSYNC_Destruct },
    CcNode_Deletable
};
const CcObjectType_t * node_sync = (const CcObjectType_t *)&NodeSYNC;

static void
CcNodeSEM_Construct(CcObject_t * self, va_list ap)
{
    CcNodeSEM_t * ccself = (CcNodeSEM_t *)self;
    ccself->pos = va_arg(ap, CcsPosition_t *);
}
static void
CcNodeSEM_Destruct(CcObject_t * self)
{
    CcNodeSEM_t * ccself = (CcNodeSEM_t *)self;
    if (ccself->pos) CcsPosition_Destruct(ccself->pos);
    CcNode_Destruct(self);
}
static const CcNodeType_t NodeSEM = {
    { sizeof(CcNodeSEM_t), "node_sem", CcNodeSEM_Construct, CcNodeSEM_Destruct },
    CcNode_Deletable
};
const CcObjectType_t * node_sem = (const CcObjectType_t *)&NodeSEM;

static void
CcNodeRSLV_Construct(CcObject_t * self, va_list ap)
{
    CcNodeRSLV_t * ccself = (CcNodeRSLV_t *)self;
    ccself->pos = va_arg(ap, CcsPosition_t *);
}
static void
CcNodeRSLV_Destruct(CcObject_t * self)
{
    CcNodeRSLV_t * ccself = (CcNodeRSLV_t *)self;
    if (ccself->pos) CcsPosition_Destruct(ccself->pos);
    CcNode_Destruct(self);
}
static const CcNodeType_t NodeRSLV = {
    { sizeof(CcNodeRSLV_t), "node_rslv", CcNodeRSLV_Construct, CcNodeRSLV_Destruct },
    CcNode_Deletable
};
const CcObjectType_t * node_rslv = (const CcObjectType_t *)&NodeRSLV;
