# -*- python -*-
# Author: Ken Zhao <kentoo.zhao@gmail.com>
# License: GPLv2.
import os.path

Import('env')
Import('CocoXml')
Import('XmlScannerFrame', 'XmlParserFrame')

env.Command(['XmlScanner.cxx', 'XmlParser.cxx'], [CocoXml, 'rss.atg'],
            './${SOURCES[0]} -frames ${SOURCES[0].srcdir} -namespace cocoxml ${SOURCES[1]}')

env.Depends('XmlScanner.cxx', XmlScannerFrame)
env.Depends('XmlParser.cxx', XmlParserFrame)

#env.Program('samples', ['Main.cpp', 'RSSData.cpp', 'XmlScanner.cpp', 'XmlParser.cpp'])
